services:
  navidrome:
    image: deluan/navidrome:latest
    user: 1000:1000
    env_file: .env
    ports:
      - "${ND_PORT}:4533"
    restart: unless-stopped
    environment:
      ND_ADDRESS: 0.0.0.0
      ND_SCAN_SCHEDULE: "@every 24h"
      ND_LOGLEVEL: info
      ND_ENABLETRANSCODINGCONFIG: "true"
      ND_TRANSCODINGCACHESIZE: "1GB"
      ND_IMAGECACHESIZE: "100MB"
      TZ: Asia/Tomsk
    volumes:
      - ./data:/data
      - ./music:/music:ro

  sync-worker:
    build: ./syncworker
    user: 1000:1000
    env_file: .env
    restart: unless-stopped
    network_mode: host
    environment:
      - XDG_CACHE_HOME=/tmp/.cache
      - TZ=Asia/Tomsk
    volumes:
      - ./music:/music
    depends_on:
      - navidrome

  python-sync-worker:
    build: ./python_syncworker
    user: 1000:1000
    env_file: .env
    restart: unless-stopped
    environment:
      MUSIC_DIR: /music
      PLAYLISTS_DIR: /music/playlists
      ARCHIVE_FILE: /music/archive.txt
      ND_BASE_URL: http://navidrome:4533/rest
      XDG_CACHE_HOME: /tmp/.cache
      TZ: Asia/Tomsk
    volumes:
      - ./music:/music
    depends_on:
      - navidrome
